language: node_js
node_js: node
services: mongodb
env:
  matrix:
    secure: fffXkWkFri9mmwjvGimNMWOdO/kuYOxGN4V9pZGIU3vLPANDf2ugifpj25jyRDdrU+XCJJcXLmKziVIWzskWz8HgZIpDFw/C5a2BmrvGxw63mDF8ZlotTWt4rvVJ0Ljg3XVXNYhgRh+tb89vcZxJBL7fFkZ/DMUMOHovWpxZVzGqcnUc4AlGKA/dk57c4uabqbblHSfYWJjP15zi+xjas2mwtI1ikDccWhofjlZuH9Rdx85vlheTLZKVHc1P62Uc5CURZNQW2UxNITSTsezrbmNzejEwv4HChcnFDH67VoFuoOUO9hpHylEeRD7N9UnpbcsTmiDj0cAqrdpzI5rFcXuFjr9MrL4RJX3Pi0wl8/muqGQzCg2zcZ6C+Bieh7CIcNG38OsyxR1je1uRJSBBjsGoXWOG5OF9DCheeOJXAhFi1AH2i4thJJ9v9NRwQYCHxUYIaDfoF/f80d7hw2dCOEE/MJwgsuWzjYiVet1rX0++1prP5d/8v1TZxJ1JtX60D4qVe645Nc2aShvXbDzEVhmO3osX6Wf2wYWkNYBPdVlKOs0Z8z0vdyhMmTcT5XRQRGQwZhTSPygKU50j6Zq381j9ubkL8zHuqZ4nAZ8fDv9yqN3J4WFIidsY4Q81FmcL6YroZXUKqlpJxJ7flX3yiv0wVl67SuprpLp1oAvj7Gk=
